#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')
Dir['*'].each do |file|
  next if file =~ /install/
  target = File.join(home, ".#{file}")
  `ln -s #{File.expand_path file} #{target}`
end

`mkdir ~/.vim/backup ~/.vim/swap ~/.vim/undo`

# install prezto shell:
# https://github.com/jcrisp/prezto/blob/master/README.md

# copy .bashrc from other computer

